sudo: false
language: node_js
node_js:
- '4.1'
deploy:
  provider: npm
  email: ikocel1@gmail.com
  api_key:
    secure: DL5P3VLyDh1cFwf1n+epA+IAlx7LHEsHxtQWWMnFcrhdg769mp0zD9chheROR6VB2R4zB2DNqCSuku0VWABNPRP2HUYDPcoqpnn0UtNocu+RDfy9lfpsGqnj1SegK611IJAwv2Q+w6fAX3Nsyo3YngWLio4eSd8aYOn88D9Atv1SQ1ZdGXeYzqTJuwASjWuQ9TJ0h8f6zvftmyxfBjtFpfdpSkImaZZ1ELugh850Ne3+mOvHhvu7ukJadOZKQU2ILCQdvVRPMlSyjeZO/qaHyH4BCiwqkqM7v2e27p7kc6uh2PyGZEprMuYYPRAJ/GctYqaF/Lpq+Mqv4imnvVR4kg17lY1KuK/UVy9NEJb88Sb/fTeMk7WL8L1T+7OET3tjjyMzHfcs8hmB89x1FF1UFR0NIHknP9vQbrTT1t8PKkixR5364IH2cAfp+vcAFR54daiLARu6Ae2oanbsaVhU3yewq1asmx9pItG8Fmno5WJWXby8nF6ztKRcUmghiXFZgtAerPK7oWmsNo2QjOyigkxRfranz6RnvBOxDRYv0skyVdohzvAmgreCgjllI7TFttpjODKYPAuSjhtgW5y9Gfnwv5py/AAKeWenLP6pJfSN45Dfctd3Z+M9BPUveXzDPXsohis96C2S0A6ZiVVlAkNG7guLHwyV9IuQvRl/Itw=
  on:
    tags: true
    repo: ferranvila/dockgrant
    branch: master
addons:
    code_climate:
        repo_token: ${CC_TOKEN}
